language: scala
scala:
  - 2.11.0
jdk:
  - oraclejdk8
services:
  - mongodb
env: MONGO_FOR_TEST=localhost:27017
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
script: sbt core/test agent/test
